### ISSUE TITLE
Request for more details about how to reproduce ZNSwap.

### ISSUE THREAD

**Issue by Haltz** [acsl-technion/znswap#2]
Hi, @shaiberg1 . ZNSwap is exciting. But I found it a little difficult for me to boot the kernel with Ubuntu 20.04. The log is as shown below. Everything was fine when using 5.13.0-generic kernel.
```
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... [   37.283766] random: fast init done
mdadm: No arrays found in config file or automatically
done.
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: error opening /dev/md?*: No such file or directory
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  UUID=66add23f-3d34-46f1-a540-ebfdd268827e does not exist.  Dropping to a shell!


BusyBox v1.30.1 (Ubuntu 1:1.30.1-4ubuntu6.4) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) 
```
madam should be something related with raid, which is not the type of my disks. Besides, btrfs is not my root filesystem (mine is ext4).  I think maybe your artifact requires these things(raid, btrfs) so znswap can not run on my system. I don't know the differences exactly between 5.12.rc3 and znswap. I would be very thankful if you could provide some suggestions on how to solve it!

**Comment by shaiberg1** [comment]
Hi @Haltz,
Thanks! I think that your fs was not compiled as part of znswaps defconfig, though you state that it is ext4...

There were no changes made to mdadm and I've not used raid... Maybe there is something in your grub config?

Did you try booting 5.16?

If you are using qemu, can you send over your run command? 

Thanks

**Comment by Haltz** [comment]
Thanks for quick reply! I'm using QEMU indeed. And my command looks like as below. FEMU is an emulator based on QEMU(I have a real ZNS SSD but I want to test it first on vm for convenience). I havn't tried boot 5.16.
```
sudo x86_64-softmmu/qemu-system-x86_64 \
    -name "FEMU-ZNSSD-VM" \
    -enable-kvm \
    -cpu host \
    -smp 32 \
    -m 32G \
    -device virtio-scsi-pci,id=scsi0 \
    -device scsi-hd,drive=hd0 \
    -drive file=$OSIMGF,if=none,aio=native,cache=none,format=qcow2,id=hd0 \
    ${FEMU_OPTIONS} \
    -net user,hostfwd=tcp::8080-:22 \
    -net nic,model=virtio \
    -nographic \
    -qmp unix:./qmp-sock,server,nowait 2>&1 | tee log
```

**Comment by shaiberg1** [comment]
I think the best way forward is to perform a diff on your working config
and merge the "yes" in the znswap config. The defconfig is a minimal config
and there could be a driver issue.

Also, you might want to try and pass the root fs to the kernel options (I
guess it might be in femu options?)

Lmk how you are getting along.

Thanks!

**Comment by Haltz** [comment]
I did as you said(merge the "yes"), but the problem still exists. I think the problem is the way I attached the root device. `-device scsi-hd,drive=hd0 -drive file=$OSIMGF,if=none,aio=native,cache=none,format=qcow2,id=hd0` maybe is not the appropriate way for znswap. I replaced it with `-hda` and followed your suggestion to pass the `root=/dev/sda`. Now I can boot znswap.

Thanks for your patience!

**Comment by shaiberg1** [comment]
Glad it is resolved.
Lmk if I can help further down the line
