### ISSUE TITLE
Request for some help to reproduce fig.10 in the paper?

### ISSUE THREAD

**Issue by Haltz** [acsl-technion/znswap#3]
Hi, @shaiberg1 I tried running vm-scalability to reproduce fig.10 in the paper. However, I'm unfamiliar with vm-scalability and found it a little difficult for me to reproduce fig.10. I know these issues are not related to znswap. but could you provide me with some suggestions? I will also try to solve them for myself, but your suggestions can really help a lot if you like.

- First, I installed vm-scalability. The scripts use `sh` as their interpreter, but `sh` can not correctly identify some commands in them. Have you run into similar issues? I think this issue should not happen in a mature benchmark(maybe I did something wrong?).
- Second, I replace sh with bash. Before running the benchmark, I followed the procedures to use zns ssd as a swap device(set nr_swap_zones, mkswap, swapon). The script reported that some files were not existent such as `/proc/lock_stats`. The readme of vm-scalability suggests that some additional configurations should be set such as  CONFIG_LOCK_STAT=y CONFIG_GCOV_KERNEL=y CONFIG_GCOV_PROFILE_ALL=y CONFIG_PERF_EVENTS=y CONFIG_FTRACE_SYSCALLS=y. But znswap does not set them. Are these necessary?
- Third, the script used xfs at default to mount tmpfs. It seemed odd......

Thanks very much if you could help!

**Comment by shaiberg1** [comment]
Hi!

1. I didn't run into the interpreter issues - but you can run the bin
directly without .sh files (that is what I did for more control over the
parameters)
2. no need to configure all these - they are just for additional kernel
statistics
3. yap, but no need for that

Since these issues are not ZNSwap related, lets take them offline so I can
be of more help.
Please email me ***@***.***) and close the issue if you agree :)

thanks

**Comment by shaiberg1** [comment]
I just saw that it crossed out my email address, were you able to find it?

**Comment by Haltz** [comment]
I think the address written in issue #1  is your current email address.  I plan to use that address but now I'm trying to figure out the scripts and parameters so I can describe my problem more accurately. Thanks!
